#!/bin/sh
#
# Automatically open up an ssh tunnel and configure OS X to use the
# connection as a SOCKS server.

localport=$RANDOM
remoteuser="ssh_user_here"
remoteproxy="ip_or_hostname_here"
remoteport="22"

if [ $1 == "on" ]; then
  echo "Listening on localhost:$localport. Modifying network settings.."
  sudo networksetup -setsocksfirewallproxy Wi-Fi 127.0.0.1 $localport off
  echo "Starting SSH session. Will run in background for 1 day."
  ssh -f -p $remoteport -D $localport $remoteuser@$remoteproxy sleep 1d
fi

if [ $1 == "off" ]; then
  echo "Disabling proxy in network settings."
  sudo networksetup -setsocksfirewallproxystate Wi-Fi off
  echo "Done!"
fi

if [ $1 == "killall" ]; then
  pids=`ps -A | grep "ssh -f" | grep "sleep" | awk '{print $1}'`
  echo "Killing all running proxy connections."
  for pid in $pids; do
    kill -9 $pid
  done
fi
